### ISSUE TITLE
add data section to Methods

### ISSUE THREAD

**Issue by orbeckst** [Becksteinlab/scipy_proceedings#24]
Add links in Methods #23  to

- [x] trajectory for test on figshare https://github.com/Becksteinlab/scipy2019-pmda-data/issues/7
- [x] scripts in https://github.com/Becksteinlab/scipy2019-pmda-data , see https://github.com/Becksteinlab/scipy2019-pmda-data/issues/5
- [x] raw data in https://github.com/Becksteinlab/scipy2019-pmda-data , see https://github.com/Becksteinlab/scipy2019-pmda-data/issues/6

(Should zenodo-wrap https://github.com/Becksteinlab/scipy2019-pmda-data.)
